
export default new Map([
["src/content/docs/components/tabs.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcomponents%2Ftabs.mdx&astroContentModuleFlag=true")],
["src/content/docs/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/components/asides.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcomponents%2Fasides.mdx&astroContentModuleFlag=true")],
["src/content/docs/components/badge.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcomponents%2Fbadge.mdx&astroContentModuleFlag=true")],
["src/content/docs/start/Errorcodes.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fstart%2FErrorcodes.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/Browser_Extension.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2FBrowser_Extension.mdx&astroContentModuleFlag=true")],
["src/content/docs/start/Quickstart.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fstart%2FQuickstart.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/review.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Freview.mdx&astroContentModuleFlag=true")],
["src/content/docs/products/ImageTasks/Binance.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fproducts%2FImageTasks%2FBinance.mdx&astroContentModuleFlag=true")],
["src/content/docs/products/ImageTasks/Imagetotext.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fproducts%2FImageTasks%2FImagetotext.mdx&astroContentModuleFlag=true")],
["src/content/docs/products/ImageTasks/Bls.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fproducts%2FImageTasks%2FBls.mdx&astroContentModuleFlag=true")],
["src/content/docs/products/ImageTasks/Mtcaptcha.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fproducts%2FImageTasks%2FMtcaptcha.mdx&astroContentModuleFlag=true")],
["src/content/docs/products/ImageTasks/GeetestV3.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fproducts%2FImageTasks%2FGeetestV3.mdx&astroContentModuleFlag=true")],
["src/content/docs/products/ImageTasks/GeetestV4.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fproducts%2FImageTasks%2FGeetestV4.mdx&astroContentModuleFlag=true")],
["src/content/docs/products/ImageTasks/Awswaf.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fproducts%2FImageTasks%2FAwswaf.mdx&astroContentModuleFlag=true")],
["src/content/docs/products/Token/GeeTestv4.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fproducts%2FToken%2FGeeTestv4.mdx&astroContentModuleFlag=true")],
["src/content/docs/products/ImageTasks/Tiktok.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fproducts%2FImageTasks%2FTiktok.mdx&astroContentModuleFlag=true")],
["src/content/docs/products/Token/Cloudflare.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fproducts%2FToken%2FCloudflare.mdx&astroContentModuleFlag=true")],
["src/content/docs/products/Token/MtCaptcha.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fproducts%2FToken%2FMtCaptcha.mdx&astroContentModuleFlag=true")],
["src/content/docs/products/ImageTasks/Recaptcha.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fproducts%2FImageTasks%2FRecaptcha.mdx&astroContentModuleFlag=true")],
["src/content/docs/products/Token/Turnstile.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fproducts%2FToken%2FTurnstile.mdx&astroContentModuleFlag=true")]]);
		